# example netlify.toml
[build]
  command = "yarn bundle"
  functions = "netlify/functions"
  publish = "."
  base = "server/"

[functions]
  node_bundler = "esbuild"
  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"